import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api'
import { resultClass, classificationClass, fmtDate, fmtAF } from '../lib'

export default function ReportDetail() {
  const { reportId } = useParams()
  const [rep, setRep] = useState(null)
  const [history, setHistory] = useState([])
  const [audit, setAudit] = useState([])
  const [err, setErr] = useState(null)

  useEffect(() => {
    setRep(null); setErr(null)
    api.report(reportId).then(setRep).catch((e) => setErr(e.message))
    api.history(reportId).then(setHistory).catch(() => {})
    api.audit(reportId).then(setAudit).catch(() => {})
  }, [reportId])

  if (err) return <div className="error">Failed to load: {err}</div>
  if (!rep) return <div className="loading">Loading report…</div>

  const prov = rep.provenance || {}

  return (
    <>
      <div className="crumbs"><Link className="link" to="/">← All reports</Link></div>

      <div className="report-head">
        <div>
          <h1 className="page-title">{rep.report_id}</h1>
          <div className="muted">{rep.test_name} · {rep.panel_name}</div>
        </div>
        <span className={`badge lg ${resultClass(rep.overall_result)}`}>{rep.overall_result}</span>
      </div>
      <div className="result-summary">{rep.result_summary}</div>

      <div className="grid2">
        <Card title="Patient">
          <Field k="Name" v={rep.patient_name} />
          <Field k="MRN" v={rep.patient_mrn} mono />
          <Field k="DOB" v={fmtDate(rep.patient_dob)} mono />
          <Field k="Sex" v={rep.patient_sex} />
          <Field k="Ordering provider" v={rep.ordering_provider} />
          <Field k="Clinic" v={rep.clinic_name} />
          <Field k="Indication" v={rep.indication} />
        </Card>
        <Card title="Case / order">
          <Field k="Case" v={rep.case_id} mono />
          <Field k="Order" v={rep.order_id} mono />
          <Field k="Accession" v={rep.accession_number} mono />
          <Field k="Reference build" v={rep.reference_build} />
          <Field k="Status" v={rep.status} />
          <Field k="Version" v={'v' + rep.version} />
          <Field k="Analyst / Director" v={`${rep.analyst_id} / ${rep.director_id}`} />
          <Field k="Reported" v={fmtDate(rep.reported_date)} mono />
        </Card>
      </div>

      <Card title={`Reported variants (${rep.variants.length})`}>
        <table className="table">
          <thead>
            <tr>
              <th>Gene</th><th>HGVS</th><th>Zygosity</th><th>Classification</th>
              <th>ClinVar</th><th>gnomAD AF</th><th className="num">Internal</th>
            </tr>
          </thead>
          <tbody>
            {rep.variants.map((v) => (
              <tr key={v.report_variant_id}>
                <td className="mono strong">{v.gene_symbol}</td>
                <td className="mono">{v.hgvs_c}<div className="muted">{v.hgvs_p}</div></td>
                <td>{v.zygosity}</td>
                <td>
                  <span className={`badge ${classificationClass(v.classification)}`}>{v.classification || '—'}</span>
                  {v.acmg_criteria?.length ? <div className="muted mono sm">{v.acmg_criteria.join(', ')}</div> : null}
                </td>
                <td>{v.clinvar_significance || '—'}<div className="muted sm">{v.clinvar_review_status}</div></td>
                <td className="mono">{fmtAF(v.gnomad_af)}</td>
                <td className="num">{v.internal_case_count}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="interps">
          {rep.variants.map((v) => (
            <div key={'i' + v.report_variant_id} className="interp">
              <span className="mono strong">{v.gene_symbol} {v.hgvs_c}</span> — {v.interpretation}
            </div>
          ))}
        </div>
      </Card>

      <div className="grid2">
        <Card title="Provenance">
          <Field k="Pipeline" v={`${prov.pipeline_name || '—'} ${prov.pipeline_version || ''}`.trim()} />
          <Field k="Reference build" v={prov.reference_build} />
          <Field k="ClinVar" v={(prov.clinvar_versions || []).join(', ') || '—'} />
          <Field k="gnomAD" v={(prov.gnomad_versions || []).join(', ') || '—'} />
          <Field k="Source DBs" v={(prov.source_databases || []).join(', ')} />
          <Field k="Generated by" v={rep.generated_by} />
        </Card>
        <Card title="Version history & audit">
          <ul className="timeline">
            {history.map((h) => (
              <li key={h.report_id} className={h.is_current ? 'cur' : ''}>
                <span className="mono strong">v{h.version}</span> · {h.status}
                {h.is_current && <span className="tag">current</span>}
                <span className="muted mono"> {fmtDate(h.reported_date)}</span>
              </li>
            ))}
          </ul>
          <h4 className="sub-h">Audit trail</h4>
          <ul className="timeline">
            {audit.map((a) => (
              <li key={a.audit_id}>
                <span className="strong">{a.action}</span> by <span className="mono">{a.actor}</span>
                <span className="muted"> (v{a.prev_version || 0}→v{a.new_version})</span>
              </li>
            ))}
          </ul>
        </Card>
      </div>
    </>
  )
}

function Card({ title, children }) {
  return <div className="card"><div className="card-title">{title}</div>{children}</div>
}

function Field({ k, v, mono }) {
  return (
    <div className="field">
      <span className="field-k">{k}</span>
      <span className={`field-v ${mono ? 'mono' : ''}`}>{v || '—'}</span>
    </div>
  )
}
